// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqCCVFxLjqIQ_ZuBxdORGOk5251umc3gM',
    appId: '1:93213716675:web:49fe8c96d79ae0f3fa7276',
    messagingSenderId: '93213716675',
    projectId: 'healthlab-5fa81',
    authDomain: 'healthlab-5fa81.firebaseapp.com',
    storageBucket: 'healthlab-5fa81.appspot.com',
    measurementId: 'G-PE0ERQZWPM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8J4nyi_LKme12lQfpRilRe93DdR6Crjo',
    appId: '1:93213716675:android:6b63823ffc2dbbabfa7276',
    messagingSenderId: '93213716675',
    projectId: 'healthlab-5fa81',
    storageBucket: 'healthlab-5fa81.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDEUbSihRFfh8zV_i5fjYa0MHnRe5C4Fw',
    appId: '1:93213716675:ios:2355f5996fc30b26fa7276',
    messagingSenderId: '93213716675',
    projectId: 'healthlab-5fa81',
    storageBucket: 'healthlab-5fa81.appspot.com',
    iosClientId: '93213716675-2gqvjfr39drrk2l2h6p5sua7vvj0571t.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthlab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDEUbSihRFfh8zV_i5fjYa0MHnRe5C4Fw',
    appId: '1:93213716675:ios:1d0a725a8ad8b731fa7276',
    messagingSenderId: '93213716675',
    projectId: 'healthlab-5fa81',
    storageBucket: 'healthlab-5fa81.appspot.com',
    iosClientId: '93213716675-98uhk1qopm8hcme5be176ofrchf0b282.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthlab.RunnerTests',
  );
}
